version: 0.2

env:
  variables:
    ACCOUNT_ID: "600960866686"
    REGION: "us-east-1"
    REPO_NAME: "massgis-agentcore-ecr"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - 'aws --region "$REGION" ecr describe-repositories --repository-names "$REPO_NAME" >/dev/null 2>&1 || aws --region "$REGION" ecr create-repository --repository-name "$REPO_NAME"'
      - 'aws --region "$REGION" ecr get-login-password | docker login --username AWS --password-stdin "$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com"'
      - 'echo "Repo: $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG"'
  build:
    commands:
      - 'docker build -t "$REPO_NAME:latest" .'
      - 'docker tag "$REPO_NAME:latest" "$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG"'
  post_build:
    commands:
      - 'docker push "$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG"'


