version: 0.2

env:
  variables:
    ACCOUNT_ID: "600960866686"
    REGION: "us-east-1"
    REPO_NAME: "massgis-agentcore-ecr"
    # Leave IMAGE_TAG empty to auto-pick commit SHA or timestamp
    IMAGE_TAG: ""

phases:
  install:
    commands:
      - 'echo "Checking Docker availability (requires Privileged=true)..."'
      - 'docker --version || (echo "ERROR: docker not found. Enable Privileged mode in CodeBuild." && exit 1)'

  pre_build:
    commands:
      - 'echo "Ensuring ECR repo exists: $REPO_NAME"'
      - 'aws --region "$REGION" ecr describe-repositories --repository-names "$REPO_NAME" >/dev/null 2>&1 || aws --region "$REGION" ecr create-repository --repository-name "$REPO_NAME"'
      - 'echo "Logging in to Amazon ECR..."'
      - 'aws --region "$REGION" ecr get-login-password | docker login --username AWS --password-stdin "$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com"'
      - 'export REPO_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME"'
      - 'if [ -z "$IMAGE_TAG" ]; then if [ -n "$CODEBUILD_RESOLVED_SOURCE_VERSION" ]; then export IMAGE_TAG="$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c1-12)"; else export IMAGE_TAG="$(date +%Y%m%d%H%M%S)"; fi; fi'
      - 'echo "Repo URI: $REPO_URI"'
      - 'echo "Image tag: $IMAGE_TAG"'
      - 'echo "Checking for Dockerfile at repo root..."'
      - 'test -f Dockerfile || (echo "ERROR: Dockerfile not found at project root." && exit 1)'

  build:
    commands:
      - 'echo "Building image as $REPO_URI:$IMAGE_TAG ..."'
      - 'docker build --progress=plain -t "$REPO_URI:$IMAGE_TAG" .'

  post_build:
    commands:
      - 'echo "Pushing image to ECR $REPO_URI:$IMAGE_TAG ..."'
      - 'docker push "$REPO_URI:$IMAGE_TAG"'
      - 'echo "Verifying image tag in ECR..."'
      - 'aws --region "$REGION" ecr describe-images --repository-name "$REPO_NAME" --image-ids imageTag="$IMAGE_TAG"'
      - 'echo "Done. Check ECR → $REPO_NAME → tag: $IMAGE_TAG"'


